[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[metadata]
name = pysersic
version = attr: my_package.VERSION
author = Imad Pasha, Tim Miller
author_email = imad.pasha@yale.edu, timothy.miller@northwestern.edu
description = A Tool for fitting sersic profiles in python
long_description = pysersic is a Python package for fitting Sersic (and other) profiles to astronomical images using Bayesian inference. It is built using the jax framework with inference performed using the numpyro probabilistic programming library. The code is hosted on GitHub and is available open source under the MIT license.
license = MIT

[project]
name = "pysersic"
version = "0.1.3"
dependencies = ['numpy',
        'scipy',
        'matplotlib',
        'pandas',
        'astropy',
        'corner',
        'photutils>=0.16',
        'jax',
        'numpyro',
        'arviz',
        'tqdm',
        'asdf',
        ]
